Added pages for large enum settings
HGLabor/bedwars pull request #2
Opened 2021-06-12 19:08 UTC by FauxKiwi

Und noch ein paar Kleinigkeiten
z.B wird beim GUI öffnen automatisch die richtige Größe berechnet

2021-06-12 19:08 UTC, FauxKiwi commented
Übrigens: Für diese Repo gibt es noch keinen Webhook

2021-06-15 16:19 UTC, mooziii commented on build.gradle.kts
> +    maven("https://maven.enginehub.org/repo/")
Where is this used?

2021-06-15 16:21 UTC, mooziii requested changes

2021-06-15 16:21 UTC, mooziii commented on build.gradle.kts
> +    compileOnly(files("C:/Users/Simon/.m2/repository/org/bukkit/craftbukkit/1.16.5-R0.1-SNAPSHOT/craftbukkit-1.16.5.jar"))
?

2021-06-15 16:23 UTC, mooziii commented
Habe jetzt nicht verstanden wo da pages für enum settings sind. eig wollte ich es mit scroll buttons machen

2021-06-15 19:37 UTC, FauxKiwi commented on build.gradle.kts
> +    maven("https://maven.enginehub.org/repo/")
WorldEdit dependency

2021-06-15 19:37 UTC, FauxKiwi commented on build.gradle.kts
> +    compileOnly(files("C:/Users/Simon/.m2/repository/org/bukkit/craftbukkit/1.16.5-R0.1-SNAPSHOT/craftbukkit-1.16.5.jar"))
Egal

2021-06-15 19:38 UTC, FauxKiwi commented
Schau dir ein enum setting mit vielen entries an

2021-06-15 19:39 UTC, FauxKiwi commented on build.gradle.kts
> +    compileOnly(files("C:/Users/Simon/.m2/repository/org/bukkit/craftbukkit/1.16.5-R0.1-SNAPSHOT/craftbukkit-1.16.5.jar"))
Siehe outdated

2021-06-17 17:08 UTC, mooziii approved these changes

2021-06-17 17:08 UTC, merged